FROM arm64v8/alpine

EXPOSE 8111

RUN apk add openjdk11 maven git \
    && java -version \
	&& mvn -version \
	&& git --version

RUN wget https://download.jetbrains.com/teamcity/TeamCity-2021.1.3.tar.gz \
    && tar -xzf TeamCity-2021.1.3.tar.gz \
	&& rm TeamCity-2021.1.3.tar.gz \
    && rm -rf /TeamCity/buildAgent

RUN mkdir data

COPY ./start.sh ./
COPY ./healthcheck.sh ./ 

RUN chmod +x ./start.sh
RUN chmod +x ./healthcheck.sh

HEALTHCHECK --interval=30s --timeout=15s --start-period=300s CMD ./healthcheck.sh localhost 8111 401

CMD ["/bin/sh", "-c", "./start.sh start"]
